import { Gothic_A1 } from 'next/font/google';
import Sidebar from '@/components/sidebar';
import './globals.css';

export const metadata = {
  title: 'Sincan Maulana NextJS Portfolio',
  description: 'Generated by create next app',
};

const gothic = Gothic_A1({
  subsets: ['latin'],
  display: 'swap',
  weight: ['400', '500', '600', '700', '800'],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en' className={gothic.className}>
      <body>
        <div className='flex w-[1000px] mx-auto mt-20'>
          <Sidebar />
          <main>{children}</main>
        </div>
      </body>
    </html>
  );
}
